"""Local SQLite store for Bailian KB upload idempotency (kb_upload_records)."""

from kb_upload_store.db import get_kb_upload_db_path, init_kb_upload_db
from kb_upload_store.service import (
    UPLOAD_RETRY_STATUSES,
    UPLOAD_SKIP_STATUSES,
    classify_upload_skip,
    compute_law_id,
    compute_version_hash,
    extract_bailian_job_id,
    fetch_record,
    law_name_from_row,
    record_id_for,
    should_skip_upload,
    update_record_index_finish,
    update_record_index_timeout,
    update_record_index_unknown,
    update_records_index_running,
    upsert_after_add_file,
    upsert_after_upload_failure,
    update_after_index_error,
    update_after_index_submitted,
    update_after_parse_failure,
    update_after_parse_success_terminal,
)

__all__ = [
    "UPLOAD_RETRY_STATUSES",
    "UPLOAD_SKIP_STATUSES",
    "classify_upload_skip",
    "compute_law_id",
    "compute_version_hash",
    "extract_bailian_job_id",
    "fetch_record",
    "get_kb_upload_db_path",
    "init_kb_upload_db",
    "law_name_from_row",
    "record_id_for",
    "should_skip_upload",
    "update_record_index_finish",
    "update_record_index_timeout",
    "update_record_index_unknown",
    "update_records_index_running",
    "upsert_after_add_file",
    "upsert_after_upload_failure",
    "update_after_index_error",
    "update_after_index_submitted",
    "update_after_parse_failure",
    "update_after_parse_success_terminal",
]
